language: cpp
compiler:
  - g++
notifications:
  email:
    on_success: never
    on_failure: always
script:
  - sudo unlink /usr/bin/g++ && sudo ln -s /usr/bin/g++-5 /usr/bin/g++
  - cd cNVMe && ./build.sh && ./a.out
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5