version: 1.0.{build}
image: Visual Studio 2017
configuration:
- Debug
- Release
platform:
- x86
- x64
clone_depth: 10
build:
  project: cNVMe.sln
  verbosity: minimal
test_script:
- ps: Get-Childitem -Filter cNVMe.exe -Recurse| % {& $_.FullName}